"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 1000
add_newline = false
palette = "noctalia"

format = """
[](fg:surface2)$directory[](fg:surface2 bg:blue)$git_branch$git_status[](fg:blue)
[╰─](fg:subtext1)$character"""

right_format = """
[](fg:green)$python$nodejs$rust$golang$java$docker_context[](fg:blue bg:green)$nix_shell$direnv[](fg:surface2 bg:blue)$time[](fg:surface2)"""

[character]
success_symbol = "[❯](bold fg:subtext1)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:yellow)"

[directory]
style = "bold fg:text bg:surface2"
format = "[ 󰉋 $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"nixconfigs" = " cfg"

[git_branch]
symbol = ""
style = "bold fg:crust bg:blue"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bold fg:crust bg:blue"
format = "[$all_status$ahead_behind ]($style)"

[time]
disabled = false
time_format = "%R"
style = "bold fg:blue bg:surface2"
format = "[ 󰥔 $time ]($style)"

[docker_context]
symbol = ""
style = "bold fg:crust bg:green"
format = "[  $context ]($style)"

[golang]
symbol = ""
style = "bold fg:crust bg:green"
format = "[ $symbol $version ]($style)"

[java]
symbol = ""
style = "bold fg:crust bg:green"
format = "[ $symbol $version ]($style)"

[nodejs]
symbol = ""
style = "bold fg:crust bg:green"
format = "[ $symbol $version ]($style)"

[nix_shell]
symbol = ""
style = "bold fg:crust bg:blue"
format = "[ $symbol $state ]($style)"

[direnv]
disabled = false
style = "bold fg:crust bg:blue"
format = '[(\($loaded\)) ]($style)'

[python]
symbol = ""
style = "bold fg:crust bg:green"
version_format = "${raw}"
format = '[ $symbol ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bold fg:crust bg:green"
format = "[ $symbol $version ]($style)"
