# Used only before Noctalia writes its palette cache.
[palettes.noctalia]
blue = "#c4c0ff"
red = "#ffb4ab"
green = "#ebb9d0"
yellow = "#c7c4dc"
cyan = "#c7c4dc"
magenta = "#ebb9d0"
white = "#e5e1e9"
black = "#131318"
text = "#e5e1e9"
subtext1 = "#c8c5d0"
subtext0 = "#c8c5d0"
overlay2 = "#35343a"
overlay1 = "#2a292f"
overlay0 = "#2a292f"
surface2 = "#35343a"
surface1 = "#2a292f"
surface0 = "#131318"
base = "#131318"
mantle = "#131318"
crust = "#2d2960"
