font_family JetBrainsMono Nerd Font
hide_window_decorations yes
window_padding_width 10 14

# Noctalia rewrites this generated theme after each palette update.
include /home/soywater/.local/state/noctalia/themes/kitty/dankcolors.conf
