font_family Maple Mono NF CN
hide_window_decorations yes
window_padding_width 10 14

# Noctalia rewrites this generated theme after each palette update.
include /home/soywater/nixconfigs/.temp/noctalia/themes/kitty/dankcolors.conf
